package com.xstocker.tabletbrowser

import com.xstocker.tabletbrowser.policy.PolicyConfig
import com.xstocker.tabletbrowser.policy.PolicyEngine
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized
import org.junit.runners.Parameterized.Parameters

/**
 * Differential cross-check of the Kotlin port against the authoritative Dart
 * engine (`lib/policy`).
 *
 * `src/test/resources/dart_cross_check.json` was generated by running the Dart
 * engine over 14 hand-picked configurations (wildcards, strict host boundaries,
 * nested file rules, query/escape edge cases, conflict modes) times 40 URLs.
 * Each case asserts `allowed`, the `DecisionReason` wire name **and** the
 * normalised URL, so a divergence in matching, specificity resolution
 * (containment) or URL normalisation is caught, not just the final verdict.
 *
 * The fixture is regenerated from the Dart sources, never edited by hand.
 */
@RunWith(Parameterized::class)
class DartCrossCheckTest(private val vector: Vector) {

    /** One (config, URL) case with the decision the Dart engine produced. */
    class Vector(private val label: String, private val body: () -> Unit) {
        fun check() = body()
        override fun toString(): String = label
    }

    @Test
    fun matchesDartEngine() = vector.check()

    companion object {
        private val allCases: List<Vector> by lazy { buildCases() }

        @JvmStatic
        @Parameters(name = "{0}")
        fun cases(): Collection<Vector> = allCases

        private fun loadFixture(): JSONObject {
            val stream = DartCrossCheckTest::class.java.classLoader
                ?.getResourceAsStream("dart_cross_check.json")
                ?: throw IllegalStateException("dart_cross_check.json is missing from the test classpath")
            return stream.use { JSONObject(String(it.readBytes(), Charsets.UTF_8)) }
        }

        private fun toMap(value: Any?): Any? = when (value) {
            is JSONObject -> value.keys().asSequence().associateWith { key -> toMap(value.get(key)) }
            is JSONArray -> (0 until value.length()).map { toMap(value.get(it)) }
            JSONObject.NULL -> null
            else -> value
        }

        private fun buildCases(): List<Vector> {
            val fixture = loadFixture()
            val configs = fixture.getJSONObject("configs")
            val engines = HashMap<String, PolicyEngine>()
            for (name in configs.keys()) {
                val json = toMap(configs.getJSONObject(name)) as Map<*, *>
                engines[name] = PolicyEngine(PolicyConfig.fromJson(json))
            }

            val vectors = fixture.getJSONArray("cases")
            val result = ArrayList<Vector>(vectors.length())
            for (index in 0 until vectors.length()) {
                val vector = vectors.getJSONObject(index)
                val configName = vector.getString("config")
                val url = vector.getString("url")
                val allowed = vector.getBoolean("allowed")
                val reason = vector.getString("reason")
                val normalizedUrl = vector.getString("normalizedUrl")
                result.add(
                    Vector("$configName | $url") {
                        val engine = engines.getValue(configName)
                        val decision = engine.decide(url)
                        assertEquals("normalizedUrl mismatch ($configName, $url)", normalizedUrl, decision.normalizedUrl)
                        assertEquals("reason mismatch ($configName, $url)", reason, decision.reason.wire)
                        assertEquals("allowed mismatch ($configName, $url)", allowed, decision.allowed)
                    }
                )
            }
            return result
        }
    }
}
